import Link from 'next/link'

export const metadata = {
    title: 'Dynamic Page',
    description: 'Generated by create next app'
}

// const getNovels = async () => {
//     const novels = await fetch('http://novel-backend.test/api/novels')
//     const novelsData = await novels.json()
//     console.log(novelsData)

//     return novelsData
// }

export default async function DynamicPage ({ children }) {
    // const results = await getNovels()
    // console.log(results)

    return (
        // <div style={{ display: 'flex', gap: '2rem' }}>
        //     <ul>
        //         {results.data.map(({ id }, i) => (
        //             <li key={`${id}_${i}`}>
        //                 <Link href={`/novel/${id}`}>{id}</Link>
        //             </li>
        //         ))}
        //     </ul>
        //     {children}
        // </div>
        <>{children}</>
    )
}
