import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <div className='antialiased bg-[#e5e4db]'>
                    <Nav />
                    <div className='max-w-screen-lg px-4 mx-auto my-4'>
                        {children}
                    </div>
                    <div>
                        <Footer />
                    </div>
                </div>
            </body>
        </html>
    )
}
